name: Orchestrate Deployments

on:
  workflow_dispatch: # Permite executar manualmente a orquestração

jobs:
  orchestrate:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment for Lambda (Repo A)
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: owner/repo-a # Substitua pelo repositório do Lambda
          event-type: deploy

      - name: Trigger Deployment for Database Infra (Repo C)
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: owner/repo-c # Substitua pelo repositório da infra de banco de dados
          event-type: deploy

      - name: Trigger Deployment for Application (Repo D)
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: owner/repo-d # Substitua pelo repositório da aplicação
          event-type: deploy